# Generated by Django 3.0.2 on 2020-01-29 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstWidget', '0004_auto_20200129_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(default='Unknown', max_length=50, null=True, verbose_name="Agent's First Name")),
                ('last_name', models.TextField(default='Unknown', max_length=50, null=True, verbose_name="Agent's Last Name")),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.AddField(
            model_name='visitor',
            name='agent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='myFirstWidget.Agent'),
        ),
    ]
