# Generated by Django 3.0.2 on 2020-01-29 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstWidget', '0006_auto_20200129_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='agent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent', to='myFirstWidget.Agent'),
        ),
    ]
