# Generated by Django 3.0.2 on 2020-01-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstWidget', '0007_auto_20200129_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='agent_id',
        ),
    ]
